<!DOCTYPE html><!--[if lt IE 7 ]><html class="no-js ie6"<?php language_attributes(); ?>><![endif]--><!--[if IE 7 ]><html class="no-js ie7"<?php language_attributes(); ?>><![endif]--><!--[if IE 8 ]><html class="no-js ie8"<?php language_attributes(); ?>><![endif]--><!--[if (gte IE 9)|!(IE)]><!--><html class=no-js<?php language_attributes(); ?>><!--<![endif]--><script>!function(t,h,e,j,n,s){t.hj=t.hj||function(){(t.hj.q=t.hj.q||[]).push(arguments)},t._hjSettings={hjid:539732,hjsv:5},n=h.getElementsByTagName("head")[0],(s=h.createElement("script")).async=1,s.src="//static.hotjar.com/c/hotjar-"+t._hjSettings.hjid+".js?sv="+t._hjSettings.hjsv,n.appendChild(s)}(window,document)</script><script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-102775935-1","auto"),ga("send","pageview")</script><script async src=https://www.google-analytics.com/analytics.js></script><meta charset="<?php bloginfo( 'charset' ); ?>"><meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0"name=viewport><meta content=Vzc8nFFP9VcKYdqrlRngLMUmP2shcv7z52S7uL0TUbc name=google-site-verification><link href="<?php echo get_permalink(); ?>"rel=alternate hreflang=fr-fr><link href=http://gmpg.org/xfn/11 rel=profile><link href="<?php bloginfo( 'pingback_url' ); ?>"rel=pingback><!--[if lt IE 9]><script src="<?php echo esc_url( get_template_directory_uri() ); ?>/js/html5shiv.min.js"></script><script src="<?php echo esc_url( get_template_directory_uri() ); ?>/js/respond.js"></script><![endif]--><?php wp_head(); ?><body<?php body_class(); ?>><div class=page-wrapper data-scroll-speed=500><nav class="navbar navbar-default navbar-fixed-top"id=navigation-bar><div class=container-fluid><div class=navbar-header><button class=navbar-toggle data-target=#myNavbar data-toggle=collapse type=button><span class=icon-bar></span> <span class=icon-bar></span> <span class=icon-bar></span></button><?php if ( get_theme_mod( 'themeora-img-upload-logo' ) ) { ?><a href="<?php echo home_url(); ?>"class=navbar-brand><img alt="<?php the_title(); ?>"class=logo-inspirama src="<?php echo esc_url( get_theme_mod( 'themeora-img-upload-logo' ) );?>"style="max-width:<?php echo esc_attr( get_theme_mod( 'themeora-img-upload-logo-width', '200' ) ); ?>px"> </a><?php } ?></div><div class="collapse navbar-collapse"id=myNavbar><?php if ( has_nav_menu('primary_menu') ) {
                    wp_nav_menu( array(
                        'container' =>false,
                        'theme_location' => 'primary_menu',
                        'menu_class' => 'nav navbar-nav',
                        'echo' => true,
                        'before' => '',
                        'after' => '',
                        'link_before' => '',
                        'link_after' => '',
                        'depth' => 0,
                        'walker' => new themeora_Walker_Nav_Menu()
                    )); 
                } ?><ul class="nav navbar-nav navbar-right"id=myNavbar><li><div class=search-form-menu><?php get_search_form(); ?></div><li id=navigation-about><a href="<?php echo get_site_url() . '/a-propos/'; ?>">À propos</a></ul></div></div></nav>